{{- if and .Values.ipxeScripts.tftp.enabled (not .Values.ipxeScripts.tftp.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netboot.fullname" . }}-tftp-scripts
  labels:
    {{- include "netboot.labels" . | nindent 4 }}
data:
  {{- range $key, $val := omit .Values.ipxeScripts.tftp "enabled" "existingConfigMap" }}
  {{- if $val }}
  {{ $key }}: |
    {{- tpl $val $ | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if and .Values.ipxeScripts.http.enabled (not .Values.ipxeScripts.http.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netboot.fullname" . }}-http-scripts
  labels:
    {{- include "netboot.labels" . | nindent 4 }}
data:
  {{- range $key, $val := omit .Values.ipxeScripts.http "enabled" "existingConfigMap" }}
  {{- if $val }}
  {{ $key }}: |
    {{- tpl $val $ | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}