{{- if and .Values.storage.dataVolume.enabled (eq .Values.storage.dataVolume.type "pvc") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netboot.fullname" . }}-data
  labels:
    {{- include "netboot.labels" . | nindent 4 }}
    {{- with .Values.storage.dataVolume.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.storage.dataVolume.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.storage.dataVolume.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.dataVolume.size }}
  {{- if .Values.storage.dataVolume.storageClass }}
  storageClassName: {{ .Values.storage.dataVolume.storageClass }}
  {{- end }}
{{- end }}